### ISSUE TITLE
Define a name for AtomicalJS?

### ISSUE THREAD

**Issue by zilveer** [silviodelgado/AtomicalJS#1]
Hi,
some plugins depends of the name JQuery, is it possible to somehow define a name for AtomicalJS so it becomes JQuery in some way?

That would be pretty cool to have so one can make it work with for example Bootstrap 4 or other plugins which relies on JQuery name other then just `$`.

Regards Zilveer

**Comment by silviodelgado** [comment]
Your request has been integrated.
See the [playground/no-conflict.html](https://github.com/silviodelgado/AtomicalJS/blob/master/playground/no-conflict.html) file

**Comment by zilveer** [comment]
@silviodelgado thanks for that.
But I don't really get it, can you please clarify:

If a JQuery plugin relies of having JQuery initiated/loaded first can I use AtomicalJS and still use that JQuery login? 
I think the JQuery plugin will yield and say that JQuery isn't defined?

/Regards Zilveer

**Comment by silviodelgado** [comment]
@zilveer Yes! You can load jQuery and use AtomicalJS at the same time.

I fixed the `noConflict()` method.
See the [playground/no-conflict.html](https://github.com/silviodelgado/AtomicalJS/blob/master/playground/no-conflict.html) file for details on how to use it.
Regards.

**Comment by zilveer** [comment]
@silviodelgado 
I think you misunderstood me.
It is not about loading JQuery and AtomicalJS at the same time.

I want to load AtomicalJS and define it as "JQuery" since some JQuery plugins relies on the name "JQuery".
Do you get what I mean now ?

Best regards Zilveer

**Comment by silviodelgado** [comment]
@zilveer ah, ok. Sorry for the mistake!

Some plugins may run properly, but certainly not all of them, because AtomicalJS is a lightweight jQuery alternative.
All AtomicalJS existing methods were rewrited (most of them in a different way). And many other methods present in jQuery aren't available in AtomicalJS.

But now, with last fix, you can try to use your jQuery plugins. ;-)

**Comment by zilveer** [comment]
@silviodelgado 
wow great, thank you.
I will try it out today :)

Once again, thanks!
